# Default image (https://hub.docker.com/_/microsoft-dotnet-core-sdk/)
image: mcr.microsoft.com/dotnet/core/sdk:3.1
#mcr.microsoft.com/windows/servercore:1809 ?????????????????

stages:
  - build
  #- test

before_script:
  - dotnet --version

# Build
build_model:
  stage: build
  script:
    - dotnet build IMS
    - dotnet build IMS.Model
    - dotnet build IMS.Persistence
    - dotnet build IMS.ViewModel

build_view:
  stage: build
  # Windows-based docker images for .NET Framework:
  # https://hub.docker.com/_/microsoft-dotnet-framework-sdk/
  image: mcr.microsoft.com/dotnet/framework/sdk:4.8
  tags: [windows]
  script:
    - dotnet build IMS.sln

# Test
#test_model:
  #stage: test
  #script:
    #- dotnet test IMS.Test
